public class MarkovPredictionTester {
    public static void main(String[] args) {
        MarkovPrediction weatherPrediction = new MarkovPrediction();
        weatherPrediction.readData("weather.csv");
        System.out.println(weatherPrediction.predictNextState("Cloudy"));
        System.out.println(weatherPrediction.predictNextState("Cloudy"));
        System.out.println(weatherPrediction.predictNextState("Cloudy"));
        System.out.println(weatherPrediction.predictNextState("Cloudy"));
        System.out.println(weatherPrediction.predictNextState("Cloudy"));
        System.out.println(weatherPrediction.predictNextState("Cloudy"));
        System.out.println(weatherPrediction.predictNextState("Cloudy"));
        System.out.println(weatherPrediction.predictNextState("Cloudy"));
        System.out.println(weatherPrediction.predictNextState("Cloudy"));
        System.out.println(weatherPrediction.predictNextState("Cloudy"));
        System.out.println(weatherPrediction.predictNextState("Cloudy"));
        System.out.println(weatherPrediction.predictNextState("Cloudy"));
        System.out.println(weatherPrediction.predictNextState("Cloudy"));
        System.out.println(weatherPrediction.predictNextState("Cloudy"));
        System.out.println(weatherPrediction.predictNextState("Cloudy"));
        System.out.println(weatherPrediction.predictNextState("Cloudy"));
        System.out.println(weatherPrediction.predictNextState("Cloudy"));
        System.out.println(weatherPrediction.predictNextState("Cloudy"));
        System.out.println(weatherPrediction.predictNextState("Cloudy"));
        System.out.println(weatherPrediction.predictNextState("Cloudy"));
        System.out.println(weatherPrediction.predictNextState("Cloudy"));
        System.out.println(weatherPrediction.predictNextState("Cloudy"));
        System.out.println(weatherPrediction.predictNextState("Cloudy"));
        System.out.println(weatherPrediction.predictNextState("Cloudy"));
        System.out.println(weatherPrediction.predictNextState("Cloudy"));
        System.out.println(weatherPrediction.predictNextState("Cloudy"));
        System.out.println(weatherPrediction.predictNextState("Cloudy"));
        System.out.println(weatherPrediction.predictNextState("Cloudy"));
        System.out.println("\n");
        System.out.println(weatherPrediction.predictNextState("Sunny"));
        System.out.println(weatherPrediction.predictNextState("Sunny"));
        System.out.println(weatherPrediction.predictNextState("Sunny"));
        System.out.println(weatherPrediction.predictNextState("Sunny"));
        System.out.println(weatherPrediction.predictNextState("Sunny"));
        System.out.println(weatherPrediction.predictNextState("Sunny"));
        System.out.println(weatherPrediction.predictNextState("Sunny"));
        System.out.println(weatherPrediction.predictNextState("Sunny"));
        System.out.println(weatherPrediction.predictNextState("Sunny"));
        System.out.println(weatherPrediction.predictNextState("Sunny"));
        System.out.println(weatherPrediction.predictNextState("Sunny"));
        System.out.println(weatherPrediction.predictNextState("Sunny"));
        System.out.println(weatherPrediction.predictNextState("Sunny"));
        System.out.println(weatherPrediction.predictNextState("Sunny"));
        System.out.println(weatherPrediction.predictNextState("Sunny"));
        System.out.println(weatherPrediction.predictNextState("Sunny"));
        System.out.println(weatherPrediction.predictNextState("Sunny"));
        System.out.println(weatherPrediction.predictNextState("Sunny"));
        System.out.println(weatherPrediction.predictNextState("Sunny"));
        System.out.println(weatherPrediction.predictNextState("Sunny"));
        System.out.println(weatherPrediction.predictNextState("Sunny"));
        System.out.println(weatherPrediction.predictNextState("Sunny"));
        System.out.println(weatherPrediction.predictNextState("Sunny"));
        System.out.println(weatherPrediction.predictNextState("Sunny"));
        System.out.println("\n");
        System.out.println(weatherPrediction.predictNextState("Thunderstorm"));
        System.out.println(weatherPrediction.predictNextState("Thunderstorm"));
        System.out.println(weatherPrediction.predictNextState("Thunderstorm"));
        System.out.println(weatherPrediction.predictNextState("Thunderstorm"));
        System.out.println(weatherPrediction.predictNextState("Thunderstorm"));
        System.out.println(weatherPrediction.predictNextState("Thunderstorm"));
        System.out.println(weatherPrediction.predictNextState("Thunderstorm"));
        System.out.println(weatherPrediction.predictNextState("Thunderstorm"));
        System.out.println(weatherPrediction.predictNextState("Thunderstorm"));
        System.out.println(weatherPrediction.predictNextState("Thunderstorm"));
        System.out.println(weatherPrediction.predictNextState("Thunderstorm"));
        System.out.println(weatherPrediction.predictNextState("Thunderstorm"));
        System.out.println(weatherPrediction.predictNextState("Thunderstorm"));
        System.out.println(weatherPrediction.predictNextState("Thunderstorm"));
        System.out.println(weatherPrediction.predictNextState("Thunderstorm"));


        // MarkovPrediction activitiesPrediction = new MarkovPrediction();

        // System.out.println(activitiesPrediction.predictNextState("Sleeping"));
    }
}
